export const thirdPartyJSFilePaths = [
  '/assets/js/jquery.min.js',
  '/assets/js/bootstrap.bundle.min.js',
  '/assets/vendor/overlay-scroll/jquery.overlayScrollbars.min.js',
  '/assets/vendor/overlay-scroll/custom-scrollbar.js',
  //   '/assets/vendor/toastify/toastify.js',
  //   '/assets/vendor/toastify/custom.js',
  '/assets/vendor/apex/apexcharts.min.js',
  '/assets/vendor/apex/custom/dash1/visitors.js',
  '/assets/vendor/apex/custom/dash1/sales.js',
  '/assets/vendor/apex/custom/dash1/orders.js',
  '/assets/vendor/apex/custom/dash1/sparkline.js',
  '/assets/vendor/apex/custom/dash1/tasks.js',
  '/assets/vendor/jvectormap/jquery-jvectormap-2.0.5.min.js',
  '/assets/vendor/jvectormap/gdp-data.js',
  '/assets/vendor/jvectormap/us_aea.js',
  '/assets/vendor/jvectormap/usa.js',
  '/assets/vendor/jvectormap/custom/map-usa4.js',
  '/assets/js/custom.js',
];
